export const questions = [
  {
    key: "myDepartment",
    questionMain: "질문 1",
    questionSub: "를 선택해주세요",
    emphaticWord: "본인의 학과",
    options: [
      { value: "인문계열" },
      { value: "자연계열" },
      { value: "예체능계열" },
    ],
  },
  {
    key: "myStyle",
    questionMain: "질문 2",
    questionSub: "를 입력해주세요",
    emphaticWord: "본인의 나이",
    emphaticWord2: "본인의 키",
    options: [],
  },
  {
    key: "myStyle",
    questionMain: "질문 3 ",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인의 스타일",
    options: [
      { value: "청순" },
      { value: "귀염" },
      { value: "섹시" },
      { value: "댄디" },
    ],
    multioption: true,
  },
  {
    questionMain: "질문 4",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인을 닮은 동물",
    options: [],
    multioption: true,
  },
  {
    key: "myWorkOut",
    questionMain: "질문 5",
    questionSub: "칠 수 있나요?",
    emphaticWord: "3대 500",
    options: [{ value: "O" }, { value: "X" }],
  },
  {
    key: "myIsSmoking",
    questionMain: "질문 6",
    questionSub: "를 선택해주세요",
    emphaticWord: "본인의 흡연유무",
    options: [{ value: "흡연" }, { value: "비흡연" }],
  },
  {
    key: "myT",
    questionMain: "질문 7",
    questionSub: "야?",
    emphaticWord: "너 T",
    options: [{ value: "O" }, { value: "겠냐?" }],
  },
];
