export const questions = [
  {
    key: "myDepartment",
    questionMain: "질문 1",
    questionSub: "를 선택해주세요",
    emphaticWord: "본인의 학과",
    options: [{ value: "예체대" }, { value: "공대" }, { value: "인문대" }],
  },
  {
    key: "myStyle",
    questionMain: "질문 2",
    questionSub: "를 입력해주세요",
    emphaticWord: "본인의 나이",
    emphaticWord2: "본인의 키",
    options: [],
  },
  {
    key: "myIsDoubleEyelid",
    questionMain: "질문 3",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인의 스타일",
    options: [{ value: "유쌍" }, { value: "무쌍" }],
    multioption: false,
  },
  {
    key: "myStyle",
    questionMain: "질문 4",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인의 스타일",
    options: [
      { value: "청순" },
      { value: "귀염" },
      { value: "섹시" },
      { value: "댄디" },
    ],
    multioption: true,
  },
  {
    key: "myHairStyle",
    questionMain: "질문 5",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인의 머리스타일",
    options: [
      { value: "단발" },
      { value: "중발" },
      { value: "장발" },
      { value: "덮머" },
      { value: "깐머" },
    ],
    multioption: true,
  },
  {
    questionMain: "질문 6",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인을 닮은 동물",
    options: [],
    multioption: true,
  },
  {
    key: "myWorkOut",
    questionMain: "질문 7",
    questionSub: "칠 수 있나요?",
    emphaticWord: "3대 500",
    options: [{ value: "O" }, { value: "X" }],
  },
  {
    key: "myCommunicationStyle",
    questionMain: "질문 8",
    questionSub: "을 선택해주세요",
    emphaticWord: "본인의 연락 스타일",
    options: [{ value: "카톡" }, { value: "전화" }],
    multioption: true,
  },
  {
    key: "myIsSmoking",
    questionMain: "질문 9",
    questionSub: "를 선택해주세요",
    emphaticWord: "본인의 흡연유무",
    options: [{ value: "흡연" }, { value: "비흡연" }],
  },
  {
    key: "myPhone",
    questionMain: "질문 10",
    questionSub: "뭐 쓰시나요?",
    emphaticWord: "핸드폰 ",
    options: [{ value: "아이폰" }, { value: "갤럭시" }, { value: "기타" }],
  },
  {
    key: "myT",
    questionMain: "질문 11",
    questionSub: "야?",
    emphaticWord: "T",
    options: [{ value: "O" }, { value: "겠냐?" }],
  },
];
