export const questions = [
  {
    questionMain: "질문 1",
    questionSub: "를 선택해주세요",
    emphaticWord: "학과",
    options: [{ value: "예체대" }, { value: "공대" }, { value: "인문대" }],
  },
  {
    questionMain: "질문 2",
    questionSub: "를 입력해주세요",
    emphaticWord: "나이",
    options: [{ value: "연상" }, { value: "연하" }, { value: "동갑" }],
  },
  {
    questionMain: "질문 3",
    questionSub: "을 선택해주세요",
    emphaticWord: "스타일",
    options: [{ value: "무쌍" }, { value: "유쌍" }],
    multioption: true,
  },
  {
    questionMain: "질문 4",
    questionSub: "을 선택해주세요",
    emphaticWord: "스타일",
    options: [
      { value: "청순" },
      { value: "귀염" },
      { value: "섹시" },
      { value: "댄디" },
    ],
    multioption: true,
  },
  {
    questionMain: "질문 5",
    questionSub: "을 선택해주세요",
    emphaticWord: "머리스타일",
    options: [
      { value: "단발" },
      { value: "중발" },
      { value: "장발" },
      { value: "덮머" },
      { value: "깐머" },
    ],
    multioption: true,
  },
  {
    questionMain: "질문 6",
    questionSub: "을 선택해주세요",
    emphaticWord: "닮은 동물",
    options: [],
    multioption: true,
  },
  {
    questionMain: "질문 7",
    questionSub: "치나요?",
    emphaticWord: "3대 500",
    options: [{ value: "O" }, { value: "X" }],
  },
  {
    questionMain: "질문 8",
    questionSub: "을 선택해주세요",
    emphaticWord: "연락 스타일",
    options: [{ value: "카톡" }, { value: "전화" }],
    multioption: true,
  },
  {
    questionMain: "질문 9",
    questionSub: "를 선택해주세요",
    emphaticWord: "흡연유무",
    options: [{ value: "흡연" }, { value: "비흡연" }],
  },
  {
    questionMain: "질문 10",
    questionSub: "뭐 쓰시나요?",
    emphaticWord: "핸드폰",
    options: [{ value: "아이폰" }, { value: "갤럭시" }, { value: "기타" }],
  },
  {
    questionMain: "질문 11",
    questionSub: "야?",
    emphaticWord: "T",
    options: [{ value: "O" }, { value: "겠냐?" }],
  },
];
