export const questions = [
  {
    key: "idealDepartment",
    questionMain: "질문 1",
    questionSub: "를 선택해주세요",
    emphaticWord: "이상형의 학과",
    options: [{ value: "예체대" }, { value: "공대" }, { value: "인문대" }],
    multioption: true,
  },
  {
    key: "idealAge",
    questionMain: "질문 2",
    questionSub: "를 선택해주세요",
    emphaticWord: "이상형의 나이",
    options: [{ value: "연상" }, { value: "연하" }, { value: "동갑" }],
    multioption: true,
  },
  {
    key: "idealHeight",
    questionMain: "질문 3",
    questionSub: "을 선택해주세요",
    emphaticWord: "이상형의 키",
    options: [
      { value: "내 키-5cm" },
      { value: "내 키-10cm" },
      { value: "내 키+5cm" },
      { value: "내 키+10cm" },
    ],
    multioption: true,
  },
  {
    key: "idealIsDoubleEyelid",
    questionMain: "질문 4",
    questionSub: "을 선택해주세요",
    emphaticWord: "이상형 스타일",
    options: [{ value: "유쌍" }, { value: "무쌍" }],
    multioption: true,
  },
  {
    key: "idealStyle",
    questionMain: "질문 5",
    questionSub: "을 선택해주세요",
    emphaticWord: "이상형 스타일",
    options: [
      { value: "청순" },
      { value: "귀염" },
      { value: "섹시" },
      { value: "댄디" },
    ],
    multioption: true,
  },
  {
    key: "idealHairStyle",
    questionMain: "질문 6",
    questionSub: "을 선택해주세요",
    emphaticWord: "이상형의 머리스타일",
    options: [
      { value: "단발" },
      { value: "중발" },
      { value: "장발" },
      { value: "덮머" },
      { value: "깐머" },
    ],
    multioption: true,
  },
  {
    key: "idealSimilarAnimals",
    questionMain: "질문 7",
    questionSub: "을 선택해주세요",
    emphaticWord: "좋아하는 동물상",
    options: [],
    multioption: true,
  },
  {
    key: "idealWorkOut",
    questionMain: "질문 8",
    questionSub: "좋으세요?",
    emphaticWord: "3대 500",
    options: [{ value: "O" }, { value: "X" }],
    multioption: true,
  },
  {
    key: "idealCommunicationStyle",
    questionMain: "질문 9",
    questionSub: "을 선택해주세요",
    emphaticWord: "이상형 연락 스타일",
    options: [{ value: "카톡" }, { value: "전화" }],
    multioption: true,
  },
  {
    key: "idealIsSmoking",
    questionMain: "질문 10",
    questionSub: "를 선택해주세요",
    emphaticWord: "이상형의 흡연유무",
    options: [{ value: "흡연" }, { value: "비흡연" }],
    multioption: true,
  },
  {
    key: "idealPhone",
    questionMain: "질문 11",
    questionSub: "뭐가 좋으세요?",
    emphaticWord: "이상형 핸드폰",
    options: [{ value: "아이폰" }, { value: "갤럭시" }, { value: "기타" }],
    multioption: true,
  },
  {
    key: "idealT",
    questionMain: "질문 12",
    questionSub: "가 좋으세요?",
    emphaticWord: "T",
    options: [{ value: "O" }, { value: "겠냐?" }],
    multioption: true,
  },
];
