export let data = {
  myKeyword: {
    myHeight: 0,
    myAge: 0,
    myStyle: [],
    myHairStyle: [],
    myIsDoubleEyelid: true,
    mySimilarAnimals: [],
    myDepartment: "",
    myWorkOut: true,
    myIsSmoking: true,
    myCommunicationStyle: [],
    myPhone: "",
    myT: true,
  },
  idealKeyword: {
    idealHeight: [],
    idealAge: "",
    idealStyle: [],
    idealHairStyle: [],
    idealIsDoubleEyelid: true,
    idealSimilarAnimals: [],
    idealDepartment: "",
    idealWorkOut: true,
    idealIsSmoking: true,
    idealCommunicationStyle: [],
    idealPhone: "",
    idealT: true,
  },
};
